export var DATA = [
{
    id: "0",
    name: 'Momo Ramen',
    description: 'Japanische Standardgerichte wie Nudelsuppe und Gyoza-Teigtaschen sowie Sake und Highballs in trendigem Lokal.',
    url: 'https://www.momo-ramen.de/',
    street: 'Margaretenstraße 58',
    zipcode: '20357 Hamburg',
    image: require('./assets/pictures/MomoRamen.jpg'),
    foodoptions: 'Omni',
    isFav: false,
    route: {latitude: 53.56638570251932, longitude: 9.963323005018351}
},
{
    id: "1",
    name: 'Momo Buns',
    description: 'Asiatische Burger und Streetfood',
    url: 'https://momo-buns.de/',
    street: 'Margaretenstraße 58',
    zipcode: '20357 Hamburg',
    image: require('./assets/pictures/MomoBuns.jpg'),
    foodoptions: 'Omni',
    isFav: false,
    route: {latitude: 53.56638570251932, longitude: 9.963323005018351}
},

{
    id: "3",
    name: 'Mexico Straße',
    description: 'Tacos und Guacamole sowie Tequila und Mezcal',
    url: 'https://www.mexikostrasse.com/',
    street: 'Eppendorfer Weg 188',
    zipcode: '20253 Hamburg',
    image: require('./assets/pictures/MexikoStrasse.jpg'),
    foodoptions: 'Omni',
    isFav: false,
    route: {latitude: 53.581173584012745, longitude: 9.970354505018983}
},
{
    id: "4",
    name: 'Altes Mädchen',
    description: 'Hausgemachtes Brot, Bio-Burger und Craft-Biere in einem rustikalen Braugasthaus mit Terasse',
    url: 'https://altes-maedchen.com/de/',
    street: 'Lagerstraße 28B',
    zipcode: '20357 Hamburg',
    image: require('./assets/pictures/AltesMaedchen.jpg'),
    foodoptions: 'Omni',
    isFav: false,
    route: {latitude: 53.56330254132214, longitude: 9.967981454378128}
},
{
    id: "5",
    name: 'Xeôm Eatery',
    description: 'Leichte vietnamesische Salate, Nudelgerichte und Pho-Suppen in einem lebhaften Retsaurant mit Industrieambiente',
    url: 'https://www.facebook.com/people/Xe%C3%94m-Eatery/100063592238260/',
    street: 'Karolinenstraße 25',
    zipcode: '20357 Hamburg',
    image: require('./assets/pictures/Xeom.jpg'),
    foodoptions: 'Omni',
    isFav: false,
    route: {latitude: 53.55942573626914, longitude: 9.975272471567594}
},
{
    id: "6",
    name: 'Dulfs Burgerladen',
    description: 'Im zeitgemäß designten Imbisslokal gibt es hausgemachte Burger aus Premium-Rind und Beilagen aus Bio-Zutaten.',
    url: 'https://www.facebook.com/people/Xe%C3%94m-Eatery/100063592238260/',
    street: 'Karolinenstraße 2',
    zipcode: '20357 Hamburg',
    image: require('./assets/pictures/DulfsBurgerladen.jpg'),
    foodoptions: 'Omni',
    isFav: false,
    route: {latitude: 53.55717603543767, longitude: 9.975208098479465}
},
{
    id: "7",
    name: 'Hatari',
    description: 'Flammkuchen, Spätzle oder Burgervariationen werden in der Gaststätte mit Dielenboden und Geweihen serviert.',
    url: 'https://hataripfaelzerstube.com/',
    street: 'Schanzenstraße 2-4',
    zipcode: '20357 Hamburg',
    image: require('./assets/pictures/Hatari.jpg'),
    foodoptions: 'Omni',
    isFav: false,
    route: {latitude: 53.55951747239896, longitude: 9.964579732733952}
},
{
    id: "8",
    name: 'Pizza Bande',
    description: 'Kreativ belegte Pizzen mit Kichererbsen, Lachs und Curry sowie vegane und süße Variationen.',
    url: 'https://www.pizza-bande.de/',
    street: 'Lincolnstraße 10',
    zipcode: '20359 Hamburg',
    image: require('./assets/pictures/PizzaBande.jpg'),
    foodoptions: 'Omni',
    isFav: false,
    route: {latitude: 53.54911921855988, longitude: 9.957548198554802}
},
{
    id: "9",
    name: 'Jils Pizza',
    description: 'Holzofenpizzen mit dünnem Boden nach neapolitanischer Art in einer Pizzeria mit Tischen im Innenhof.',
    url: 'https://www.jill.hamburg/#/',
    street: 'Bartelsstraße 12',
    zipcode: '20357 Hamburg',
    image: require('./assets/pictures/JilsPizza.jpg'),
    foodoptions: 'Omni',
    isFav: false,
    route: {latitude: 53.562154055634466, longitude: 9.964961883213565}
},
{
    id: "10",
    name: 'Tazzi Pizza',
    description: 'Wein, Salate, Vorspeisen und eine Auswahl an Pizza in gemütlichem italienischem Lokal.',
    url: 'https://www.tazzipizza.com/',
    street: 'Rendsburger Str. 14',
    zipcode: '20359 Hamburg',
    image: require('./assets/pictures/TazziPizza.jpg'),
    foodoptions: 'Omni',
    isFav: false,
    route: {latitude: 53.55210058013061, longitude: 9.964521912048625}
},

{
    id: "11",
    name: 'Grilly Idol',
    description: 'Burgers, Pommes frites und Salate sowie Kaffee, Wein und Bier in farbenfrohem Lokal.',
    url: 'https://grilly-idol.de/',
    street: 'Clemens-Schultz-Straße 40',
    zipcode: '20359 Hamburg',
    image: require('./assets/pictures/GrillyIdol.jpg'),
    foodoptions: 'Omni',
    isFav: false,
    route: {latitude: 53.552546751545705, longitude: 9.962118652915548}
},
{
    id: "12",
    name: 'Azeitona',
    description: 'Zwangloses libanesisches Lokal mit veganen Vorspeisentellern, Dips, Salaten und Falafel-Sandwiches.',
    url: 'https://azeitona.de/',
    street: 'Beckstraße 17',
    zipcode: '20357 Hamburg',
    image: require('./assets/pictures/Azeitona.jpg'),
    foodoptions: 'Veggie',
    isFav: false,
    route: {latitude: 53.55904182897171, longitude: 9.965245612048832}
},
{
    id: "13",
    name: 'Ume no Hana',
    description: 'Zwangloses Restaurant mit japanischen und vietnamesischen Nudelspeisen, Gyoza-Teigtaschen und Frühlingsrollen.',
    url: 'https://www.umenohana-hamburg.de/',
    street: 'Thadenstraße 15',
    zipcode: '22767 Hamburg',
    image: require('./assets/pictures/UmeNoHana.jpg'),
    foodoptions: 'Omni',
    isFav: false,
    route: {latitude: 53.55651069158446, longitude: 9.961639083213377}
},
{
    id: "14",
    name: 'Falafel Stern',
    description: 'Der arabische Imbiss mit Gastraum und orientalischem Flair serviert Falafel und überwiegend vegetarische Kost.',
    url: 'http://www.falafelstern.de/arabisch-vegetarisch-imbiss/imbiss-partyservice-hamburg.php',
    street: 'Schanzenstraße 111',
    zipcode: '20357 Hamburg',
    image: require('./assets/pictures/FalaffelStern.jpg'),
    foodoptions: 'Veggie',
    isFav: false,
    route: {latitude: 53.56454379290617, longitude: 9.965405527390667}
},
{
    id: "15",
    name: 'Kimo',
    description: 'Einfaches Restaurant, bekannt für Falafel und andere mediterrane und ägyptische Spezialitäten.',
    url: 'https://www.falafel-kimo.com/',
    street: 'Schanzenstraße 111',
    zipcode: '20357 Hamburg',
    image: require('./assets/pictures/Kimo.jpg'),
    foodoptions: 'Omni',
    isFav: false,
    route: {latitude: 53.564538285220145, longitude: 9.965199002051948}
},
{
    id: "16",
    name: 'Surolls',
    description: 'Sushi Burritos - Die gesunde Fast Food Alternative',
    url: 'https://surolls.com/',
    street: 'Ballindamm 40',
    zipcode: '20095 Hamburg',
    image: require('./assets/pictures/Surolls.jpg'),
    foodoptions: 'Omni',
    isFav: false,
    route: {latitude: 53.55157077802492, longitude: 9.996157229238175}
},

{
    id: "17",
    name: 'Nord Coast Coffee Roastery',
    description: 'Die Kaffeerösterei aus Hamburg, bietet neben frisch gerösteten Kaffee auch leckeres Frühstück und mehr.',
    url: 'https://www.nordcoast-coffee.de/',
    street: 'Deichstraße 9',
    zipcode: '20459 Hamburg',
    image: require('./assets/pictures/NordCoastRoastery.jpg'),
    foodoptions: 'Omni',
    isFav: false,
    route: {latitude: 53.547044027382434, longitude: 9.988089973017512}
},
{
    id: "18",
    name: 'Tassajara',
    description: 'Gehobene vegetarische und vegane Speisen mit asiatischer Note in schickem Restaurant mit weißen Tischdecken.',
    url: 'https://www.tassajara.de/',
    street: 'Eppendorfer Landstraße 4',
    zipcode: '20249 Hamburg',
    image: require('./assets/pictures/Tassajara.jpg'),
    foodoptions: 'Vegan',
    isFav: false,
    route: {latitude: 53.58523875670472, longitude: 9.982128803334685}
},
{
    id: "19",
    name: 'Erdapfel',
    description: 'Ungezwungenes Restaurant für Ofenkartoffeln mit unterschiedlicher vegetarischer Füllung.',
    url: 'https://erdapfel-hamburg.de/',
    street: 'Buchardstraße 10',
    zipcode: '20095 Hamburg',
    image: require('./assets/pictures/Erdapfel.jpg'),
    foodoptions: 'Veggie',
    isFav: false,
    route: {latitude: 53.555892225900465, longitude: 10.00389498176028}
},
{
    id: "20",
    name: 'Café Johanna',
    description: 'Frühstück, Sandwiches, Salate, Kaffee und Kuchen in einem coolen, minimalistischen Café in einem alten Kiosk.',
    url: 'https://cafejohanna.de',
    street: 'Venusberg 26',
    zipcode: '20459 Hamburg',
    image: require('./assets/pictures/CafeJohanna.jpg'),
    foodoptions: 'Veggie',
    isFav: false,
    route: {latitude: 53.54723234633136, longitude: 9.975014811962064}
},
{
    id: "21",
    name: 'Mamalicious',
    description: 'Buntes Café mit vegetarischen und veganen Gerichten von Pancakes und Eiern bis zu pflanzlicher Currywurst.',
    url: 'https://mamaknows.de',
    street: 'Max-Brauer-Allee 277',
    zipcode: '22769 Hamburg',
    image: require('./assets/pictures/Mamalicious.jpg'),
    foodoptions: 'Veggie',
    isFav: false,
    route: {latitude: 53.56390020619442, longitude: 9.959443737474846}
},
{
    id: "22",
    name: 'Apple & Eve',
    description: 'Pflanzlich zubereitete Fast-Food-Klassiker in einem modernen Lokal mit ungezwungener Atmosphäre.',
    url: 'https://www.appleeve.de/',
    street: 'Schanzenstraße 107',
    zipcode: '20357 Hamburg',
    image: require('./assets/pictures/AppleAndEve.jpg'),
    foodoptions: 'Vegan',
    isFav: false,
    route: {latitude: 53.56443704350161, longitude: 9.96525779514735}
},
{
    id: "23",
    name: 'Golden Temple Teehaus',
    description: 'Frühstück, Currys und Kuchen in einem geselligen veganen Café mit zusammengewürfelten Möbeln und Gartentischen.',
    url: 'https://www.gt-teehaus.de/',
    street: 'Grindelallee 26',
    zipcode: '20146 Hamburg',
    image: require('./assets/pictures/GoldenTempleTeehaus.jpg'),
    foodoptions: 'Vegan',
    isFav: false,
    route: {latitude: 53.565117433235216, longitude: 9.983704005187704}
},
{
    id: "24",
    name: 'Bodhi - vegan living',
    description: 'Gemütliches asiatisches Restaurant mit veganem Sushi, Salaten und Gerichten zum Teilen sowie Getränken.',
    url: 'https://bodhihamburg.de',
    street: 'Borgweg 11',
    zipcode: '22303 Hamburg',
    image: require('./assets/pictures/Bodhi.jpg'),
    foodoptions: 'Vegan',
    isFav: false,
    route: {latitude: 53.59040072953907, longitude: 10.01527545614466}
},
{
    id: "25",
    name: 'Loving Hut',
    description: 'Vegane Fast-Food-Restaurantkette mit asiatischer Speisekarte.',
    url: 'https://lovinghut.de',
    street: 'Ferdinand-Breit-Straße 7',
    zipcode: '20099 Hamburg',
    image: require('./assets/pictures/LovingHut.jpg'),
    foodoptions: 'Vegan',
    isFav: false,
    route: {latitude: 53.554753291685174, longitude: 10.019397755372399}
},
{
    id: "26",
    name: 'ÆNDRÈ',
    description: 'Heimeliges Café mit Terrasse, Frühstücks- und Mittagsgerichte für Gesundheitsbewusste sowie Desserts.',
    url: 'https://aendre.de',
    street: 'Lehmweg 31A',
    zipcode: '20251 Hamburg',
    image: require('./assets/pictures/Aendre.jpg'),
    foodoptions: 'Vegan',
    isFav: false,
    route: {latitude: 53.58259807446299, longitude: 9.979542611963096}
},
{
    id: "27",
    name: 'Very Very Veggie Vegan Sushi',
    description: 'Leckeres Veganes Sushi',
    url: 'https://veggie-vegan-sushi.de',
    street: 'Barmbeker Str. 3',
    zipcode: '22303 Hamburg',
    image: require('./assets/pictures/VeryVeryVeggieVeganSushi.jpg'),
    foodoptions: 'Vegan',
    isFav: false,
    route: {latitude: 53.58258075189473, longitude: 10.019150257998149}
},
{
    id: "28",
    name: 'An Vegan House',
    description: 'Hippes veganes Restaurant mit asiatischen Nudelgerichten, Suppen und Currys sowie Shakes und erfrischenden Cocktails.',
    url: 'https://www.facebook.com/anveganhouse/',
    street: 'Mühlenkamp 19',
    zipcode: '22303 Hamburg',
    image: require('./assets/pictures/AnVeganHouse.jpg'),
    foodoptions: 'Vegan',
    isFav: false,
    route: {latitude: 53.58210221908184, longitude: 10.011626323902316}
},
{
    id: "29",
    name: 'Cai Kitchen',
    description: 'In einem modernem hippen, angesagtem Design überzeugen Gerichte aus lokalen Produkten im klassichen Sichuan-Stil.',
    url: 'https://caikitchen.de/',
    street: 'Glashüttenstraße 85a',
    zipcode: '20357 Hamburg',
    image: require('./assets/pictures/CaiKitchen.jpg'),
    foodoptions: 'Vegan',
    isFav: false,
    route: {latitude: 53.559637018025015, longitude: 9.973129027307438}
},
{
    id: "30",
    name: 'Happenpappen',
    description: 'Vegane Burger, Bowls, Kuchen und Quiches in einem hippen Lokal mit Zimmerpflanzen und hellen Holztischen.',
    url: 'http://happenpappen.de/home/gerichte/',
    street: 'Feldstraße 36',
    zipcode: '20357 Hamburg',
    image: require('./assets/pictures/Happenpappen.jpg'),
    foodoptions: 'Vegan',
    isFav: false,
    route: {latitude: 53.55758601675445, longitude: 9.970293891696155}
},
{
    id: "31",
    name: 'The Vegan Eagle',
    description: 'Kreative, vegane Küche mit internationalem Touch sowie Craftbier und Ale in gut besuchtem Restaurant mit Biergarten.',
    url: 'https://theveganeagle.com',
    street: 'Wischhöfen 4',
    zipcode: '22415 Hamburg',
    image: require('./assets/pictures/VeganEagle.jpg'),
    foodoptions: 'Vegan',
    isFav: false,
    route: {latitude: 53.644653539355026, longitude: 10.01226926963761}
},
{
    id: "32",
    name: 'Froindlichst',
    description: 'Veganes Restaurant mit Pizza, Burgern, Burritos, Salaten, modernem Holzinterieur und Lieferservice',
    url: 'https://froindlichst.com',
    street: 'Barmbeker Str. 169',
    zipcode: '22299 Hamburg',
    image: require('./assets/pictures/Froindlichst.jpg'),
    foodoptions: 'Vegan',
    isFav: false,
    route: {latitude: 53.59325926983483, longitude: 10.002615921048065}
},

{
    id: "33",
    name: 'Soul',
    description: 'Pancakes, Smoothie-Bowls, Kaffee und Kuchen sowie Mittagsangebote in trendigem veganem Restaurant.',
    url: 'https://soul-vegan.de',
    street: 'Eppendorfer Landstraße 109',
    zipcode: '20251 Hamburg',
    image: require('./assets/pictures/Soul.jpg'),
    foodoptions: 'Vegan',
    isFav: false,
    route: {latitude: 53.599284178915354, longitude: 9.990105332255487}
},
{
    id: "34",
    name: 'Katers Köök',
    description: 'Einfaches Restaurant, bekannt für Falafel und andere mediterrane und ägyptische Spezialitäten.',
    url: 'https://katers-koeoek.de',
    street: 'Kleiner Schäferkamp 24',
    zipcode: '20357 Hamburg',
    image: require('./assets/pictures/KatersKoeoek.jpg'),
    foodoptions: 'Vegan',
    isFav: false,
    route: {latitude: 53.56727114252147, longitude: 9.968428983126355}
},
{
    id: "35",
    name: 'Nasch',
    description: 'Vegetarische und vegane Sandwiches und Salate sowie Kaffee und Tee in unkonventionellem, rustikal-elegantem Café.',
    url: 'https://cafenasch.de',
    street: 'Caffamacherreihe 49',
    zipcode: '20355 Hamburg',
    image: require('./assets/pictures/Nasch.jpg'),
    foodoptions: 'Veggie',
    isFav: false,
    route: {latitude: 53.555430742028236, longitude: 9.983867440798544}
}

];
